-- Add
DROP EVENT IF EXISTS post_audit;
DELIMITER $$
CREATE EVENT IF NOT EXISTS post_audit
  ON SCHEDULE
    EVERY 1 WEEK
    STARTS CURRENT_DATE
DO BEGIN
  DELETE FROM post WHERE createdAt < DATE_ADD(CURDATE(), INTERVAL -7 day);
END $$
DELIMITER ;